/**
 * Academic LaTeX & Typst Exporter
 * Generates publication-ready, clean LaTeX code (compatible with Overleaf / pdfLaTeX / XeLaTeX)
 */

export interface LatexExportData {
  fullName: string;
  email: string;
  phone?: string;
  location?: string;
  linkedin?: string;
  github?: string;
  education: Array<{
    institution: string;
    degree: string;
    location: string;
    graduationDate: string;
    gpa?: string;
    coursework?: string[];
  }>;
  experience: Array<{
    company: string;
    role: string;
    location: string;
    dates: string;
    bullets: string[];
  }>;
  skills: Array<{
    category: string;
    items: string[];
  }>;
}

export function generateAcademicLatex(data: LatexExportData): string {
  const sanitize = (text?: string) =>
    (text || "")
      .replace(/\\/g, "\\textbackslash{}")
      .replace(/[%$&_#{}]/g, "\\$&")
      .replace(/~/g, "\\textasciitilde{}")
      .replace(/\^/g, "\\textasciicircum{}");

  const eduItems = data.education
    .map(
      (e) => `
\\resumeSubheading
  {${sanitize(e.institution)}}{${sanitize(e.location)}}
  {${sanitize(e.degree)}}{${sanitize(e.graduationDate)}}
  ${e.gpa ? `\\resumeItem{Cumulative GPA: ${sanitize(e.gpa)}}` : ""}
  ${e.coursework && e.coursework.length ? `\\resumeItem{Relevant Coursework: ${sanitize(e.coursework.join(", "))}}` : ""}`
    )
    .join("\n");

  const expItems = data.experience
    .map(
      (exp) => `
\\resumeSubheading
  {${sanitize(exp.company)}}{${sanitize(exp.location)}}
  {${sanitize(exp.role)}}{${sanitize(exp.dates)}}
  \\resumeItemListStart
    ${exp.bullets.map((b) => `\\resumeItem{${sanitize(b)}}`).join("\n    ")}
  \\resumeItemListEnd`
    )
    .join("\n");

  const skillItems = data.skills
    .map(
      (s) => `\\textbf{${sanitize(s.category)}: } {${sanitize(s.items.join(", "))}} \\\\`
    )
    .join("\n  ");

  return `%-------------------------
% Academic Resume in LaTeX
% Generated by ResumeForge
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}

\\pagestyle{fancy}
\\fancyhf{} 
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\newcommand{\\resumeItem}[1]{\\item\\small{{#1 \\vspace{-2pt}}}}
\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}[leftmargin=0.15in, label={$\\bullet$}]}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

\\begin{document}

\\begin{center}
    \\textbf{\\Huge \\scshape ${sanitize(data.fullName)}} \\\\ \\vspace{1pt}
    \\small ${sanitize(data.phone)} $|$ \\href{mailto:${sanitize(data.email)}}{${sanitize(data.email)}} $|$ 
    ${data.linkedin ? `\\href{${data.linkedin}}{linkedin.com} $|$ ` : ""}
    ${data.github ? `\\href{${data.github}}{github.com} $|$ ` : ""}
    ${sanitize(data.location)}
\\end{center}

\\section{Education}
  \\begin{itemize}[leftmargin=0.15in, label={}]
    ${eduItems}
  \\end{itemize}

\\section{Experience}
  \\begin{itemize}[leftmargin=0.15in, label={}]
    ${expItems}
  \\end{itemize}

\\section{Technical Skills}
  \\small{
    ${skillItems}
  }

\\end{document}
`;
}
