/**
 * Comprehensive Directory of Colleges & Universities in the Commonwealth of Virginia
 * Includes:
 * - 15 Public 4-Year Research Universities & Colleges
 * - 12 Major Private Universities & Colleges
 * - ALL 23 Virginia Community College System (VCCS) Institutions
 *
 * Each record provides:
 * - Official branding, slug, acronyms, and regional location
 * - Institution category (VCCS Community College, Public University, Private University)
 * - Academic domains and student/faculty email patterns (RocketReach verified)
 * - Institution Canvas LMS URL (pre-configured for instant verification)
 * - Top majors & transfer pathways
 */

export interface VirginiaInstitution {
  name: string;
  slug: string;
  shortName: string;
  category: "vccs_community_college" | "public_university" | "private_university";
  domain: string;
  emailDomains: string[];
  emailFormat: string;
  sampleEmail: string;
  location: string;
  region: string;
  canvasUrl: string;
  website: string;
  undergrads: string;
  placementRate: string;
  avgStartingSalary: string;
  topMajors: string[];
  formats: Array<{ pattern: string; example: string; percentage: string }>;
  transferPartners?: string[];
}

export const VIRGINIA_INSTITUTIONS: VirginiaInstitution[] = [
  // ─── 1. VIRGINIA 4-YEAR PUBLIC UNIVERSITIES (15) ──────────────────────────
  {
    name: "Old Dominion University",
    slug: "old-dominion-university",
    shortName: "ODU",
    category: "public_university",
    domain: "odu.edu",
    emailDomains: ["odu.edu", "cs.odu.edu"],
    emailFormat: "[username]@odu.edu",
    sampleEmail: "[username]@odu.edu",
    location: "Norfolk, VA",
    region: "Hampton Roads / Coastal Virginia",
    canvasUrl: "https://canvas.odu.edu",
    website: "https://www.odu.edu",
    undergrads: "24,000+",
    placementRate: "88%",
    avgStartingSalary: "$78,500",
    topMajors: ["Computer Science", "Cybersecurity", "Mechanical Engineering", "Business Analytics", "Nursing", "Finance"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@odu.edu", percentage: "84.4%" },
      { pattern: "[first][last]", example: "janedoe@odu.edu", percentage: "3.5%" },
      { pattern: "[first][last_initial]", example: "janed@odu.edu", percentage: "2.9%" },
      { pattern: "[username]@odu.edu", example: "[username]@odu.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "University of Virginia",
    slug: "university-of-virginia",
    shortName: "UVA",
    category: "public_university",
    domain: "virginia.edu",
    emailDomains: ["virginia.edu", "cs.virginia.edu"],
    emailFormat: "[computing_id]@virginia.edu",
    sampleEmail: "[username]@virginia.edu",
    location: "Charlottesville, VA",
    region: "Central Virginia",
    canvasUrl: "https://canvas.its.virginia.edu",
    website: "https://www.virginia.edu",
    undergrads: "17,500+",
    placementRate: "93%",
    avgStartingSalary: "$89,000",
    topMajors: ["Computer Science", "Economics", "Commerce / McIntire", "Data Science", "Biomedical Engineering"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@virginia.edu", percentage: "64.2%" },
      { pattern: "[computing_id]@virginia.edu", example: "[username]@virginia.edu", percentage: "Student ID" },
      { pattern: "[first].[last]", example: "jane.doe@virginia.edu", percentage: "22.5%" },
    ],
  },
  {
    name: "Virginia Tech",
    slug: "virginia-tech",
    shortName: "VT",
    category: "public_university",
    domain: "vt.edu",
    emailDomains: ["vt.edu", "cs.vt.edu"],
    emailFormat: "[pid]@vt.edu",
    sampleEmail: "[username]@vt.edu",
    location: "Blacksburg, VA",
    region: "Southwest / New River Valley",
    canvasUrl: "https://canvas.vt.edu",
    website: "https://www.vt.edu",
    undergrads: "30,000+",
    placementRate: "92%",
    avgStartingSalary: "$88,000",
    topMajors: ["Computer Science", "Computer Engineering", "Mechanical Engineering", "Business Information Tech", "Architecture"],
    formats: [
      { pattern: "[pid]@vt.edu", example: "[username]@vt.edu", percentage: "Primary (PID)" },
      { pattern: "[first_initial][last]", example: "jdoe@vt.edu", percentage: "72.1%" },
      { pattern: "[first].[last]", example: "jane.doe@vt.edu", percentage: "18.4%" },
    ],
  },
  {
    name: "George Mason University",
    slug: "george-mason-university",
    shortName: "GMU",
    category: "public_university",
    domain: "gmu.edu",
    emailDomains: ["gmu.edu", "masonlive.gmu.edu"],
    emailFormat: "[username]@masonlive.gmu.edu",
    sampleEmail: "[username]@masonlive.gmu.edu",
    location: "Fairfax, VA",
    region: "Northern Virginia (NOVA)",
    canvasUrl: "https://canvas.gmu.edu",
    website: "https://www.gmu.edu",
    undergrads: "27,000+",
    placementRate: "89%",
    avgStartingSalary: "$82,000",
    topMajors: ["Information Technology", "Computer Science", "Cybersecurity Engineering", "Government & Politics", "Data Analytics"],
    formats: [
      { pattern: "[username]@masonlive.gmu.edu", example: "[username]@masonlive.gmu.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@gmu.edu", percentage: "71.0%" },
      { pattern: "[first].[last]", example: "jane.doe@gmu.edu", percentage: "19.2%" },
    ],
  },
  {
    name: "Virginia Commonwealth University",
    slug: "virginia-commonwealth-university",
    shortName: "VCU",
    category: "public_university",
    domain: "vcu.edu",
    emailDomains: ["vcu.edu", "mymail.vcu.edu"],
    emailFormat: "[eid]@mymail.vcu.edu",
    sampleEmail: "[username]@mymail.vcu.edu",
    location: "Richmond, VA",
    region: "Greater Richmond / Capital Region",
    canvasUrl: "https://canvas.vcu.edu",
    website: "https://www.vcu.edu",
    undergrads: "21,000+",
    placementRate: "87%",
    avgStartingSalary: "$76,000",
    topMajors: ["Computer Science", "Biomedical Engineering", "Pre-Medicine", "Graphic Design", "Business Administration"],
    formats: [
      { pattern: "[eid]@mymail.vcu.edu", example: "[username]@mymail.vcu.edu", percentage: "Student Portal" },
      { pattern: "[last][first_initial]", example: "doej@vcu.edu", percentage: "62.5%" },
      { pattern: "[first_initial][last]", example: "jdoe@vcu.edu", percentage: "25.3%" },
    ],
  },
  {
    name: "College of William & Mary",
    slug: "william-and-mary",
    shortName: "W&M",
    category: "public_university",
    domain: "wm.edu",
    emailDomains: ["wm.edu", "email.wm.edu"],
    emailFormat: "[username]@email.wm.edu",
    sampleEmail: "[username]@email.wm.edu",
    location: "Williamsburg, VA",
    region: "Historic Triangle / Coastal Virginia",
    canvasUrl: "https://canvas.wm.edu",
    website: "https://www.wm.edu",
    undergrads: "6,500+",
    placementRate: "92%",
    avgStartingSalary: "$84,000",
    topMajors: ["Computer Science", "Data Science", "Finance / Mason School", "Government", "Biology"],
    formats: [
      { pattern: "[username]@email.wm.edu", example: "[username]@email.wm.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@wm.edu", percentage: "79.0%" },
      { pattern: "[first].[last]", example: "jane.doe@wm.edu", percentage: "15.0%" },
    ],
  },
  {
    name: "James Madison University",
    slug: "james-madison-university",
    shortName: "JMU",
    category: "public_university",
    domain: "jmu.edu",
    emailDomains: ["jmu.edu", "dukes.jmu.edu"],
    emailFormat: "[e-ID]@dukes.jmu.edu",
    sampleEmail: "[username]@dukes.jmu.edu",
    location: "Harrisonburg, VA",
    region: "Shenandoah Valley",
    canvasUrl: "https://canvas.jmu.edu",
    website: "https://www.jmu.edu",
    undergrads: "20,000+",
    placementRate: "90%",
    avgStartingSalary: "$75,000",
    topMajors: ["Computer Science", "Information Technology", "Finance", "Nursing", "Media Arts & Design"],
    formats: [
      { pattern: "[e-ID]@dukes.jmu.edu", example: "[username]@dukes.jmu.edu", percentage: "Student Dukes" },
      { pattern: "[last][first_initial][middle_initial]", example: "doejm@jmu.edu", percentage: "68.4%" },
    ],
  },
  {
    name: "Christopher Newport University",
    slug: "christopher-newport-university",
    shortName: "CNU",
    category: "public_university",
    domain: "cnu.edu",
    emailDomains: ["cnu.edu"],
    emailFormat: "[first].[last]@cnu.edu",
    sampleEmail: "[username]@cnu.edu",
    location: "Newport News, VA",
    region: "Hampton Roads / Coastal Virginia",
    canvasUrl: "https://canvas.cnu.edu",
    website: "https://www.cnu.edu",
    undergrads: "4,500+",
    placementRate: "89%",
    avgStartingSalary: "$72,000",
    topMajors: ["Computer Science", "Information Science", "Business Administration", "Political Science"],
    formats: [
      { pattern: "[first].[last]", example: "jane.doe@cnu.edu", percentage: "82.0%" },
      { pattern: "[first_initial][last]", example: "jdoe@cnu.edu", percentage: "14.0%" },
    ],
  },
  {
    name: "Radford University",
    slug: "radford-university",
    shortName: "Radford",
    category: "public_university",
    domain: "radford.edu",
    emailDomains: ["radford.edu"],
    emailFormat: "[username]@radford.edu",
    sampleEmail: "[username]@radford.edu",
    location: "Radford, VA",
    region: "New River Valley",
    canvasUrl: "https://canvas.radford.edu",
    website: "https://www.radford.edu",
    undergrads: "7,500+",
    placementRate: "85%",
    avgStartingSalary: "$68,000",
    topMajors: ["Computer Science & Tech", "Cybersecurity", "Nursing", "Criminal Justice"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@radford.edu", percentage: "76.0%" },
      { pattern: "[username]@radford.edu", example: "[username]@radford.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Longwood University",
    slug: "longwood-university",
    shortName: "Longwood",
    category: "public_university",
    domain: "longwood.edu",
    emailDomains: ["longwood.edu", "live.longwood.edu"],
    emailFormat: "[username]@live.longwood.edu",
    sampleEmail: "[username]@live.longwood.edu",
    location: "Farmville, VA",
    region: "Southside Virginia",
    canvasUrl: "https://canvas.longwood.edu",
    website: "https://www.longwood.edu",
    undergrads: "4,000+",
    placementRate: "84%",
    avgStartingSalary: "$65,000",
    topMajors: ["Business Administration", "Computer Science", "Education", "Kinesiology"],
    formats: [
      { pattern: "[first].[last]", example: "jane.doe@live.longwood.edu", percentage: "72.0%" },
      { pattern: "[first_initial][last]", example: "jdoe@longwood.edu", percentage: "22.0%" },
    ],
  },
  {
    name: "Norfolk State University",
    slug: "norfolk-state-university",
    shortName: "NSU",
    category: "public_university",
    domain: "nsu.edu",
    emailDomains: ["nsu.edu", "spartans.nsu.edu"],
    emailFormat: "[username]@spartans.nsu.edu",
    sampleEmail: "[username]@spartans.nsu.edu",
    location: "Norfolk, VA",
    region: "Hampton Roads (HBCU)",
    canvasUrl: "https://canvas.nsu.edu",
    website: "https://www.nsu.edu",
    undergrads: "5,500+",
    placementRate: "83%",
    avgStartingSalary: "$70,000",
    topMajors: ["Computer Science", "Cybersecurity", "Business Management", "Nursing", "Social Work"],
    formats: [
      { pattern: "[username]@spartans.nsu.edu", example: "[username]@spartans.nsu.edu", percentage: "Spartan Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@nsu.edu", percentage: "74.0%" },
    ],
  },
  {
    name: "Virginia State University",
    slug: "virginia-state-university",
    shortName: "VSU",
    category: "public_university",
    domain: "vsu.edu",
    emailDomains: ["vsu.edu", "students.vsu.edu"],
    emailFormat: "[username]@students.vsu.edu",
    sampleEmail: "[username]@students.vsu.edu",
    location: "Petersburg, VA",
    region: "Central Virginia (HBCU)",
    canvasUrl: "https://canvas.vsu.edu",
    website: "https://www.vsu.edu",
    undergrads: "4,200+",
    placementRate: "82%",
    avgStartingSalary: "$66,000",
    topMajors: ["Computer Science", "Mechanical Engineering Technology", "Agriculture", "Business Management"],
    formats: [
      { pattern: "[username]@students.vsu.edu", example: "[username]@students.vsu.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@vsu.edu", percentage: "75.0%" },
    ],
  },
  {
    name: "Virginia Military Institute",
    slug: "virginia-military-institute",
    shortName: "VMI",
    category: "public_university",
    domain: "vmi.edu",
    emailDomains: ["vmi.edu", "cadet.vmi.edu"],
    emailFormat: "[username]@cadet.vmi.edu",
    sampleEmail: "[username]@cadet.vmi.edu",
    location: "Lexington, VA",
    region: "Shenandoah Valley",
    canvasUrl: "https://canvas.vmi.edu",
    website: "https://www.vmi.edu",
    undergrads: "1,700+",
    placementRate: "94%",
    avgStartingSalary: "$85,000",
    topMajors: ["Civil Engineering", "Mechanical Engineering", "Computer Science", "International Studies"],
    formats: [
      { pattern: "[last][first_initial][middle_initial]", example: "doejm@cadet.vmi.edu", percentage: "Cadet Mail" },
      { pattern: "[first_initial][last]", example: "jdoe@vmi.edu", percentage: "Faculty" },
    ],
  },
  {
    name: "University of Mary Washington",
    slug: "university-of-mary-washington",
    shortName: "UMW",
    category: "public_university",
    domain: "umw.edu",
    emailDomains: ["umw.edu", "mail.umw.edu"],
    emailFormat: "[username]@mail.umw.edu",
    sampleEmail: "[username]@mail.umw.edu",
    location: "Fredericksburg, VA",
    region: "Northern Virginia / Rappahannock",
    canvasUrl: "https://canvas.umw.edu",
    website: "https://www.umw.edu",
    undergrads: "3,800+",
    placementRate: "87%",
    avgStartingSalary: "$71,000",
    topMajors: ["Computer Science", "Business Administration", "Historic Preservation", "Psychology"],
    formats: [
      { pattern: "[username]@mail.umw.edu", example: "[username]@mail.umw.edu", percentage: "Student Mail" },
      { pattern: "[first_initial][last]", example: "jdoe@umw.edu", percentage: "78.0%" },
    ],
  },
  {
    name: "UVA's College at Wise",
    slug: "uva-wise",
    shortName: "UVA Wise",
    category: "public_university",
    domain: "uvawise.edu",
    emailDomains: ["uvawise.edu"],
    emailFormat: "[username]@uvawise.edu",
    sampleEmail: "[username]@uvawise.edu",
    location: "Wise, VA",
    region: "Southwest Virginia",
    canvasUrl: "https://canvas.uvawise.edu",
    website: "https://www.uvawise.edu",
    undergrads: "2,000+",
    placementRate: "83%",
    avgStartingSalary: "$64,000",
    topMajors: ["Software Engineering", "Computer Science", "Administration of Justice", "Business"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@uvawise.edu", percentage: "72.0%" },
      { pattern: "[username]@uvawise.edu", example: "[username]@uvawise.edu", percentage: "Student Portal" },
    ],
  },

  // ─── 2. ALL 23 VIRGINIA COMMUNITY COLLEGE SYSTEM (VCCS) INSTITUTIONS ─────
  {
    name: "Tidewater Community College",
    slug: "tidewater-community-college",
    shortName: "TCC",
    category: "vccs_community_college",
    domain: "tcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "tcc.edu", "email.tcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Norfolk, Virginia Beach, Chesapeake, Portsmouth, VA",
    region: "Hampton Roads / Coastal Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.tcc.edu",
    undergrads: "20,000+",
    placementRate: "86%",
    avgStartingSalary: "$62,000",
    topMajors: ["Computer Science AS", "Cybersecurity AAS", "Information Technology", "Business Administration AS", "Nursing AAS", "Engineering AS"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@tcc.edu", percentage: "78.2%" },
      { pattern: "[first].[last]", example: "jane.doe@tcc.edu", percentage: "14.5%" },
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
    transferPartners: ["Old Dominion University (ODU Online / On-Campus)", "Norfolk State University", "Virginia Tech", "Christopher Newport University"],
  },
  {
    name: "Northern Virginia Community College",
    slug: "northern-virginia-community-college",
    shortName: "NOVA",
    category: "vccs_community_college",
    domain: "nvcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "nvcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Annandale, Alexandria, Loudoun, Manassas, Woodbridge, VA",
    region: "Northern Virginia (NOVA)",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.nvcc.edu",
    undergrads: "50,000+",
    placementRate: "89%",
    avgStartingSalary: "$67,000",
    topMajors: ["Computer Science AS", "Cybersecurity AAS", "Cloud Computing AAS", "Business Administration AS", "Data Analytics"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@nvcc.edu", percentage: "74.0%" },
    ],
    transferPartners: ["George Mason University (ADVANCE Program)", "Virginia Tech", "University of Virginia"],
  },
  {
    name: "Virginia Peninsula Community College",
    slug: "virginia-peninsula-community-college",
    shortName: "VPCC",
    category: "vccs_community_college",
    domain: "vpcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "vpcc.edu", "tncc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Hampton, Williamsburg, VA",
    region: "Virginia Peninsula / Historic Triangle",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.vpcc.edu",
    undergrads: "7,000+",
    placementRate: "84%",
    avgStartingSalary: "$60,000",
    topMajors: ["Computer Science AS", "Cybersecurity", "Advanced Manufacturing", "Business Administration", "Engineering"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@vpcc.edu", percentage: "76.0%" },
    ],
    transferPartners: ["William & Mary", "Old Dominion University", "Christopher Newport University"],
  },
  {
    name: "J. Sargeant Reynolds Community College",
    slug: "reynolds-community-college",
    shortName: "Reynolds",
    category: "vccs_community_college",
    domain: "reynolds.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "reynolds.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Richmond, Goochland, VA",
    region: "Greater Richmond / Capital Region",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.reynolds.edu",
    undergrads: "11,000+",
    placementRate: "85%",
    avgStartingSalary: "$61,000",
    topMajors: ["Information Technology", "Computer Science AS", "Business Administration", "Culinary Arts", "Nursing"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@reynolds.edu", percentage: "72.0%" },
    ],
    transferPartners: ["Virginia Commonwealth University (VCU)", "University of Richmond"],
  },
  {
    name: "Brightpoint Community College",
    slug: "brightpoint-community-college",
    shortName: "Brightpoint",
    category: "vccs_community_college",
    domain: "brightpoint.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "brightpoint.edu", "jtcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Chester, Midlothian, VA",
    region: "Greater Richmond / Southside",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.brightpoint.edu",
    undergrads: "9,000+",
    placementRate: "85%",
    avgStartingSalary: "$61,000",
    topMajors: ["Information Technology", "Computer Science AS", "Mechanical Engineering Tech", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@brightpoint.edu", percentage: "75.0%" },
    ],
    transferPartners: ["VCU", "Virginia State University", "Longwood University"],
  },
  {
    name: "Germanna Community College",
    slug: "germanna-community-college",
    shortName: "Germanna",
    category: "vccs_community_college",
    domain: "germanna.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "germanna.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Fredericksburg, Locust Grove, Culpeper, VA",
    region: "Rappahannock / Central Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.germanna.edu",
    undergrads: "8,500+",
    placementRate: "86%",
    avgStartingSalary: "$63,000",
    topMajors: ["Computer Science AS", "Cybersecurity", "Nursing", "Business Administration", "Engineering"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@germanna.edu", percentage: "76.0%" },
    ],
    transferPartners: ["University of Mary Washington", "George Mason University", "Virginia Tech"],
  },
  {
    name: "Piedmont Virginia Community College",
    slug: "piedmont-virginia-community-college",
    shortName: "PVCC",
    category: "vccs_community_college",
    domain: "pvcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "pvcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Charlottesville, VA",
    region: "Central Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.pvcc.edu",
    undergrads: "5,000+",
    placementRate: "88%",
    avgStartingSalary: "$64,000",
    topMajors: ["Computer Science AS", "Cybersecurity", "Biotechnology", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@pvcc.edu", percentage: "78.0%" },
    ],
    transferPartners: ["University of Virginia (Direct Guaranteed Transfer)", "Virginia Tech"],
  },
  {
    name: "Blue Ridge Community College",
    slug: "blue-ridge-community-college",
    shortName: "BRCC",
    category: "vccs_community_college",
    domain: "brcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "brcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Weyers Cave, Harrisonburg, VA",
    region: "Shenandoah Valley",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.brcc.edu",
    undergrads: "4,000+",
    placementRate: "84%",
    avgStartingSalary: "$59,000",
    topMajors: ["Information Systems Tech", "Aviation Maintenance", "Nursing", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@brcc.edu", percentage: "73.0%" },
    ],
    transferPartners: ["James Madison University (JMU Transfer)", "Virginia Tech"],
  },
  {
    name: "Central Virginia Community College",
    slug: "central-virginia-community-college",
    shortName: "CVCC",
    category: "vccs_community_college",
    domain: "centralvirginia.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "centralvirginia.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Lynchburg, VA",
    region: "Central Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.centralvirginia.edu",
    undergrads: "3,800+",
    placementRate: "83%",
    avgStartingSalary: "$58,000",
    topMajors: ["Cybersecurity", "Computer Science AS", "Nuclear Technology", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@centralvirginia.edu", percentage: "74.0%" },
    ],
    transferPartners: ["University of Lynchburg", "Liberty University", "Virginia Tech"],
  },
  {
    name: "Mountain Gateway Community College",
    slug: "mountain-gateway-community-college",
    shortName: "MGCC",
    category: "vccs_community_college",
    domain: "mgcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "mgcc.edu", "dslcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Clifton Forge, Buena Vista, VA",
    region: "Alleghany Highlands / Valley",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.mgcc.edu",
    undergrads: "1,200+",
    placementRate: "82%",
    avgStartingSalary: "$56,000",
    topMajors: ["Forestry", "Information Technology", "Business Administration", "Welding"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Danville Community College",
    slug: "danville-community-college",
    shortName: "DCC",
    category: "vccs_community_college",
    domain: "danville.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "danville.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Danville, VA",
    region: "Southern Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.danville.edu",
    undergrads: "2,500+",
    placementRate: "84%",
    avgStartingSalary: "$57,000",
    topMajors: ["Precision Machining", "Cybersecurity", "Electrical Electronic Technology", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Eastern Shore Community College",
    slug: "eastern-shore-community-college",
    shortName: "ESCC",
    category: "vccs_community_college",
    domain: "es.vccs.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "es.vccs.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Melfa, VA",
    region: "Eastern Shore of Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://es.vccs.edu",
    undergrads: "900+",
    placementRate: "81%",
    avgStartingSalary: "$55,000",
    topMajors: ["Electronics Technology", "Business Administration", "Medical Assisting", "General Studies"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Laurel Ridge Community College",
    slug: "laurel-ridge-community-college",
    shortName: "Laurel Ridge",
    category: "vccs_community_college",
    domain: "laurelridge.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "laurelridge.edu", "lfcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Middletown, Warrenton, Luray, VA",
    region: "Northern Shenandoah Valley",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.laurelridge.edu",
    undergrads: "6,000+",
    placementRate: "85%",
    avgStartingSalary: "$61,000",
    topMajors: ["Cybersecurity", "Computer Science AS", "Nursing", "Engineering"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Mountain Empire Community College",
    slug: "mountain-empire-community-college",
    shortName: "MECC",
    category: "vccs_community_college",
    domain: "mecc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "mecc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Big Stone Gap, VA",
    region: "Southwest Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.mecc.edu",
    undergrads: "2,200+",
    placementRate: "82%",
    avgStartingSalary: "$56,000",
    topMajors: ["Information Systems Tech", "Mining & Industrial Tech", "Nursing", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "New River Community College",
    slug: "new-river-community-college",
    shortName: "NRCC",
    category: "vccs_community_college",
    domain: "nr.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "nr.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Dublin, Christiansburg, VA",
    region: "New River Valley",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.nr.edu",
    undergrads: "4,200+",
    placementRate: "84%",
    avgStartingSalary: "$59,000",
    topMajors: ["Instrumentation & Electrical", "Computer Science AS", "Machine Technology", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
    transferPartners: ["Virginia Tech (NRCC-VT Bridge)", "Radford University"],
  },
  {
    name: "Patrick & Henry Community College",
    slug: "patrick-henry-community-college",
    shortName: "P&HCC",
    category: "vccs_community_college",
    domain: "patrickhenry.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "patrickhenry.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Martinsville, Stuart, VA",
    region: "Southern Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.patrickhenry.edu",
    undergrads: "2,300+",
    placementRate: "81%",
    avgStartingSalary: "$55,000",
    topMajors: ["Motorsports Technology", "Industrial Electronics", "Nursing", "Administration of Justice"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Camp Community College",
    slug: "camp-community-college",
    shortName: "Camp",
    category: "vccs_community_college",
    domain: "pdc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "pdc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Franklin, Suffolk, Smithfield, VA",
    region: "Western Tidewater / Hampton Roads",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.pdc.edu",
    undergrads: "1,500+",
    placementRate: "82%",
    avgStartingSalary: "$57,000",
    topMajors: ["Industrial Technology", "Computer Support Specialist", "Nursing", "Logistics & Warehousing"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
    transferPartners: ["Old Dominion University", "Norfolk State University"],
  },
  {
    name: "Rappahannock Community College",
    slug: "rappahannock-community-college",
    shortName: "RCC",
    category: "vccs_community_college",
    domain: "rappahannock.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "rappahannock.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Glenns, Warsaw, Kilmarnock, VA",
    region: "Middle Peninsula & Northern Neck",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.rappahannock.edu",
    undergrads: "2,800+",
    placementRate: "83%",
    avgStartingSalary: "$57,000",
    topMajors: ["Marine Trades", "Information Technology", "Nursing", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Southside Virginia Community College",
    slug: "southside-virginia-community-college",
    shortName: "SVCC",
    category: "vccs_community_college",
    domain: "southside.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "southside.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Alberta, Keysville, South Hill, VA",
    region: "Southside Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.southside.edu",
    undergrads: "3,300+",
    placementRate: "82%",
    avgStartingSalary: "$56,000",
    topMajors: ["Power Line Worker Tech", "Information Technology", "Truck Driving", "Associate of Arts & Sciences"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Southwest Virginia Community College",
    slug: "southwest-virginia-community-college",
    shortName: "SWCC",
    category: "vccs_community_college",
    domain: "sw.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "sw.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Cedar Bluff, Richlands, Tazewell, VA",
    region: "Southwest Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.sw.edu",
    undergrads: "2,400+",
    placementRate: "81%",
    avgStartingSalary: "$55,000",
    topMajors: ["Unmanned Aerial Systems (Drones)", "Cybersecurity", "Nursing", "General Studies"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Virginia Highlands Community College",
    slug: "virginia-highlands-community-college",
    shortName: "VHCC",
    category: "vccs_community_college",
    domain: "vhcc.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "vhcc.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Abingdon, VA",
    region: "Southwest Virginia / Blue Ridge",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.vhcc.edu",
    undergrads: "2,100+",
    placementRate: "83%",
    avgStartingSalary: "$56,000",
    topMajors: ["Information Systems Tech", "Electrical Tech", "Horticulture", "Nursing"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },
  {
    name: "Virginia Western Community College",
    slug: "virginia-western-community-college",
    shortName: "VWCC",
    category: "vccs_community_college",
    domain: "virginiawestern.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "virginiawestern.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Roanoke, VA",
    region: "Roanoke Valley",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.virginiawestern.edu",
    undergrads: "6,200+",
    placementRate: "85%",
    avgStartingSalary: "$60,000",
    topMajors: ["Mechatronics Systems", "Computer Science AS", "Dental Hygiene", "Business Administration"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
    transferPartners: ["Virginia Tech", "Radford University", "Roanoke College"],
  },
  {
    name: "Wytheville Community College",
    slug: "wytheville-community-college",
    shortName: "WCC",
    category: "vccs_community_college",
    domain: "wcc.vccs.edu",
    emailDomains: ["email.vccs.edu", "vccs.edu", "wcc.vccs.edu"],
    emailFormat: "[username]@email.vccs.edu",
    sampleEmail: "[username]@email.vccs.edu",
    location: "Wytheville, Galax, Marion, VA",
    region: "Southwest Virginia",
    canvasUrl: "https://vccs.instructure.com",
    website: "https://www.wcc.vccs.edu",
    undergrads: "2,000+",
    placementRate: "82%",
    avgStartingSalary: "$55,000",
    topMajors: ["Physical Therapist Assistant", "Information Technology", "Machine Tool", "General Studies"],
    formats: [
      { pattern: "[username]@email.vccs.edu", example: "[username]@email.vccs.edu", percentage: "Student Portal" },
    ],
  },

  // ─── 3. MAJOR VIRGINIA PRIVATE UNIVERSITIES (12) ──────────────────────────
  {
    name: "University of Richmond",
    slug: "university-of-richmond",
    shortName: "UR",
    category: "private_university",
    domain: "richmond.edu",
    emailDomains: ["richmond.edu"],
    emailFormat: "[username]@richmond.edu",
    sampleEmail: "[username]@richmond.edu",
    location: "Richmond, VA",
    region: "Capital Region",
    canvasUrl: "https://canvas.richmond.edu",
    website: "https://www.richmond.edu",
    undergrads: "3,100+",
    placementRate: "94%",
    avgStartingSalary: "$86,000",
    topMajors: ["Business Administration (Robins)", "Computer Science", "Leadership Studies (Jepson)", "Economics"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@richmond.edu", percentage: "78.0%" },
      { pattern: "[first].[last]", example: "jane.doe@richmond.edu", percentage: "18.0%" },
    ],
  },
  {
    name: "Liberty University",
    slug: "liberty-university",
    shortName: "Liberty",
    category: "private_university",
    domain: "liberty.edu",
    emailDomains: ["liberty.edu"],
    emailFormat: "[username]@liberty.edu",
    sampleEmail: "[username]@liberty.edu",
    location: "Lynchburg, VA",
    region: "Central Virginia",
    canvasUrl: "https://canvas.liberty.edu",
    website: "https://www.liberty.edu",
    undergrads: "48,000+",
    placementRate: "87%",
    avgStartingSalary: "$72,000",
    topMajors: ["Computer Science", "Business Administration", "Aviation", "Nursing", "Cybersecurity"],
    formats: [
      { pattern: "[username]@liberty.edu", example: "[username]@liberty.edu", percentage: "Student Portal" },
      { pattern: "[first_initial][last]", example: "jdoe@liberty.edu", percentage: "72.0%" },
    ],
  },
  {
    name: "Hampton University",
    slug: "hampton-university",
    shortName: "Hampton",
    category: "private_university",
    domain: "hamptonu.edu",
    emailDomains: ["hamptonu.edu", "my.hamptonu.edu"],
    emailFormat: "[username]@my.hamptonu.edu",
    sampleEmail: "[username]@my.hamptonu.edu",
    location: "Hampton, VA",
    region: "Hampton Roads (HBCU)",
    canvasUrl: "https://canvas.hamptonu.edu",
    website: "https://www.hamptonu.edu",
    undergrads: "3,500+",
    placementRate: "88%",
    avgStartingSalary: "$74,000",
    topMajors: ["Computer Science", "Aviation Management", "Business Administration", "Pharmacy", "Journalism"],
    formats: [
      { pattern: "[first].[last]", example: "jane.doe@my.hamptonu.edu", percentage: "75.0%" },
      { pattern: "[first_initial][last]", example: "jdoe@hamptonu.edu", percentage: "20.0%" },
    ],
  },
  {
    name: "Washington and Lee University",
    slug: "washington-and-lee-university",
    shortName: "W&L",
    category: "private_university",
    domain: "wlu.edu",
    emailDomains: ["wlu.edu"],
    emailFormat: "[username]@wlu.edu",
    sampleEmail: "[username]@wlu.edu",
    location: "Lexington, VA",
    region: "Shenandoah Valley",
    canvasUrl: "https://canvas.wlu.edu",
    website: "https://www.wlu.edu",
    undergrads: "1,800+",
    placementRate: "95%",
    avgStartingSalary: "$91,000",
    topMajors: ["Business Administration (Williams)", "Computer Science", "Economics", "History", "Law"],
    formats: [
      { pattern: "[last][first_initial][grad_year]", example: "doej27@mail.wlu.edu", percentage: "Students" },
      { pattern: "[first_initial][last]", example: "jdoe@wlu.edu", percentage: "Faculty" },
    ],
  },
  {
    name: "Regent University",
    slug: "regent-university",
    shortName: "Regent",
    category: "private_university",
    domain: "regent.edu",
    emailDomains: ["regent.edu", "mail.regent.edu"],
    emailFormat: "[username]@mail.regent.edu",
    sampleEmail: "[username]@mail.regent.edu",
    location: "Virginia Beach, VA",
    region: "Hampton Roads / Coastal Virginia",
    canvasUrl: "https://canvas.regent.edu",
    website: "https://www.regent.edu",
    undergrads: "4,500+",
    placementRate: "85%",
    avgStartingSalary: "$69,000",
    topMajors: ["Cybersecurity", "Law", "Business Administration", "Communication", "Psychology"],
    formats: [
      { pattern: "[username]@mail.regent.edu", example: "[username]@mail.regent.edu", percentage: "Student Mail" },
      { pattern: "[first_initial][last]", example: "jdoe@regent.edu", percentage: "70.0%" },
    ],
  },
  {
    name: "Shenandoah University",
    slug: "shenandoah-university",
    shortName: "SU",
    category: "private_university",
    domain: "su.edu",
    emailDomains: ["su.edu"],
    emailFormat: "[username]@su.edu",
    sampleEmail: "[username]@su.edu",
    location: "Winchester, VA",
    region: "Northern Shenandoah Valley",
    canvasUrl: "https://canvas.su.edu",
    website: "https://www.su.edu",
    undergrads: "2,200+",
    placementRate: "86%",
    avgStartingSalary: "$70,000",
    topMajors: ["Esports Management", "Virtual Reality Design", "Pharmacy", "Music & Theatre", "Nursing"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@su.edu", percentage: "77.0%" },
    ],
  },
  {
    name: "Marymount University",
    slug: "marymount-university",
    shortName: "Marymount",
    category: "private_university",
    domain: "marymount.edu",
    emailDomains: ["marymount.edu"],
    emailFormat: "[username]@marymount.edu",
    sampleEmail: "[username]@marymount.edu",
    location: "Arlington, VA",
    region: "Northern Virginia (D.C. Metro)",
    canvasUrl: "https://canvas.marymount.edu",
    website: "https://www.marymount.edu",
    undergrads: "2,400+",
    placementRate: "88%",
    avgStartingSalary: "$73,000",
    topMajors: ["Cybersecurity", "Information Technology", "Nursing", "Fashion Design", "Forensic Psychology"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@marymount.edu", percentage: "78.0%" },
    ],
  },
  {
    name: "Virginia Wesleyan University",
    slug: "virginia-wesleyan-university",
    shortName: "VWU",
    category: "private_university",
    domain: "vwu.edu",
    emailDomains: ["vwu.edu"],
    emailFormat: "[username]@vwu.edu",
    sampleEmail: "[username]@vwu.edu",
    location: "Virginia Beach / Norfolk, VA",
    region: "Hampton Roads / Coastal Virginia",
    canvasUrl: "https://canvas.vwu.edu",
    website: "https://www.vwu.edu",
    undergrads: "1,400+",
    placementRate: "84%",
    avgStartingSalary: "$63,000",
    topMajors: ["Environmental Studies", "Business Administration", "Computer Science", "Biology"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@vwu.edu", percentage: "76.0%" },
    ],
  },
  {
    name: "Roanoke College",
    slug: "roanoke-college",
    shortName: "Roanoke",
    category: "private_university",
    domain: "roanoke.edu",
    emailDomains: ["roanoke.edu"],
    emailFormat: "[username]@roanoke.edu",
    sampleEmail: "[username]@roanoke.edu",
    location: "Salem, VA",
    region: "Roanoke Valley",
    canvasUrl: "https://canvas.roanoke.edu",
    website: "https://www.roanoke.edu",
    undergrads: "1,900+",
    placementRate: "87%",
    avgStartingSalary: "$67,000",
    topMajors: ["Computer Science", "Actuarial Science", "Business Administration", "Pre-Health"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@roanoke.edu", percentage: "75.0%" },
    ],
  },
  {
    name: "Bridgewater College",
    slug: "bridgewater-college",
    shortName: "Bridgewater",
    category: "private_university",
    domain: "bridgewater.edu",
    emailDomains: ["bridgewater.edu"],
    emailFormat: "[username]@bridgewater.edu",
    sampleEmail: "[username]@bridgewater.edu",
    location: "Bridgewater, VA",
    region: "Shenandoah Valley",
    canvasUrl: "https://canvas.bridgewater.edu",
    website: "https://www.bridgewater.edu",
    undergrads: "1,500+",
    placementRate: "85%",
    avgStartingSalary: "$64,000",
    topMajors: ["Information Systems Management", "Business Administration", "Health & Exercise Science"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@bridgewater.edu", percentage: "74.0%" },
    ],
  },
  {
    name: "Randolph-Macon College",
    slug: "randolph-macon-college",
    shortName: "R-MC",
    category: "private_university",
    domain: "rmc.edu",
    emailDomains: ["rmc.edu"],
    emailFormat: "[username]@rmc.edu",
    sampleEmail: "[username]@rmc.edu",
    location: "Ashland, VA",
    region: "Central Virginia (Near Richmond)",
    canvasUrl: "https://canvas.rmc.edu",
    website: "https://www.rmc.edu",
    undergrads: "1,500+",
    placementRate: "89%",
    avgStartingSalary: "$68,000",
    topMajors: ["Computer Science", "Engineering Physics", "Business Finance", "Pre-Medicine"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@rmc.edu", percentage: "76.0%" },
    ],
  },
  {
    name: "University of Lynchburg",
    slug: "university-of-lynchburg",
    shortName: "Lynchburg",
    category: "private_university",
    domain: "lynchburg.edu",
    emailDomains: ["lynchburg.edu"],
    emailFormat: "[username]@lynchburg.edu",
    sampleEmail: "[username]@lynchburg.edu",
    location: "Lynchburg, VA",
    region: "Central Virginia",
    canvasUrl: "https://canvas.lynchburg.edu",
    website: "https://www.lynchburg.edu",
    undergrads: "2,000+",
    placementRate: "86%",
    avgStartingSalary: "$65,000",
    topMajors: ["Computer Science", "Criminology", "Biomedical Science", "Business Administration"],
    formats: [
      { pattern: "[first_initial][last]", example: "jdoe@lynchburg.edu", percentage: "74.0%" },
    ],
  },
];

/**
 * Quick search helper by name, acronym, or city
 */
export function findVirginiaInstitution(query: string): VirginiaInstitution | undefined {
  if (!query || query.trim().length === 0) return undefined;
  const q = query.toLowerCase().trim();

  return VIRGINIA_INSTITUTIONS.find((inst) => {
    if (inst.name.toLowerCase() === q) return true;
    if (inst.shortName.toLowerCase() === q) return true;
    if (inst.slug.toLowerCase() === q) return true;
    if (inst.domain.toLowerCase() === q) return true;
    if (inst.name.toLowerCase().includes(q)) return true;
    if (inst.location.toLowerCase().includes(q)) return true;
    return false;
  });
}
